### PR TITLE
fix(setcookie): setCookie now sets the cookie value

### LINKED ISSUE #4: (Easy) Possibility of double setting of access token cookie
We need to make sure that the [`setCookie`](https://supertokens.io/discord) function in [cookieAndHeaders.go](https://github.com/supertokens/supertokens-go/blob/master/supertokens/cookieAndHeaders.go#L101), if given the same cookie twice, does not set it two times. Instead, the older cookie should be overwritten by the new cookie. 

For example, if I call `setCookie` with a cookie like `abc=someVal`, and then I call it again with a cookie like `abc=someOtherVal`, the final response should have just `Set-Cookie: abc=someOtherVal` and not `Set-Cookie: abc=someOtherVal; abc=someVal`

### PR DESCRIPTION
**Pull request by metallicmonkey**
This ensures setCookie replace the cookie value instead of appending it to the "Set-Cookie" header.
Tests have been added.
Fixes #4

### CODE REVIEW

**Comment by rishabhpoddar** [comment]
Thanks for the contribution. What would happen if I call `setCookieValue` with a cookie like `abc=1`, and then again with a cookie like `xyz=1`. The output should be `Set-Cookie: abc=1; xyz=1`. If this already happens, could you please add a test for this case as well?

Thanks!

**Comment by metallicmonkey** [comment]
@rishabhpoddar ensuring cookies get updated correctly and adding a test for that specific use case.

**Comment by rishabhpoddar** [comment]
I had to remove the following from the start of `setCookieValue`:
```
       if v := cookie.String(); v != "" {
               return
       }
```

**Comment by metallicmonkey** [comment]
> I had to remove the following from the start of `setCookieValue`:
> 
> ```
> if v := cookie.String(); v != "" {
>     return
> }
> ```

my bad, good catch!

**Comment by rishabhpoddar** [comment]
thanks! I will update `supertokens-core` to list you as a contributor.

**Pull request merged**
