### PR TITLE
Fixes unnecessary cookie cleanup

### PR DESCRIPTION
**Pull request by EnzoBtv**
Links to issue #13

### CODE REVIEW

**Comment by rishabhpoddar** [comment]
Hi @EnzoBtv. Thanks for the contribution. The code change seems fine, however the tests are not accurate. 
- You do not want to call the create new session API in the test and directly call the verification API. In the response, you want to check that the `extractInfoFromResponseHeader` function returns `null` for everything.
- In the API itself, you want to return `200` only if the error type if `unauthorised`.

The same applies for the refresh test. 

Thanks!

**Comment by EnzoBtv** [comment]
Fixed as you've asked!

**Comment by rishabhpoddar** [comment]
Thanks for the contribution @EnzoBtv ! I have added you in the contributor's list in supertokens-core

**Comment by EnzoBtv** [comment]
Thanks a lot! Any help needed you can message me!

**Comment by EnzoBtv** [comment]
Can you add  the hacktoberfest-accepted label to help me or add the hacktoberfest tag on the repo? :)

**Comment by EnzoBtv** [comment]
Thanks a lot :)

**Pull request merged**
